### ISSUE TITLE
marshal of nested structs results in panic

### ISSUE THREAD

**Issue by KoreyBarton** [segmentio/encoding#23]
**Description**:
Attempting to marshal a nested struct of type `struct{map[string]struct{map[string]string}}` and similarly nested structs results in a panic.

**Environment**:
Architecture: amd64
OS: darwin and linux
go version: 1.13.5
json module version: 0.1.6

**Example**:
https://play.golang.org/p/UoCOVM8Lh8g
```
package main

import (
	"github.com/segmentio/encoding/json"
)

type testInner struct {
	InnerMap map[string]string `json:"inner_map"`
}

type testOuter struct {
	OuterMap map[string]testInner `json:"outer_map"`
}

func main() {
	t := testOuter{
		map[string]testInner{
			"outer": {
				map[string]string{
					"inner": "value",
				},
			},
		},
	}
	json.Marshal(t)
}
```

resulting stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x100f42a]

goroutine 1 [running]:
reflect.maplen(0x1, 0xc000070100)
        /usr/local/go/src/runtime/map.go:1369 +0xa
reflect.Value.MapKeys(0x10f0e20, 0xc0000761b0, 0x195, 0x10f0e20, 0xc0000761b0, 0x195)
        /usr/local/go/src/reflect/value.go:1200 +0x20e
github.com/segmentio/encoding/json.encoder.encodeMap(0x3, 0xc0000a2000, 0x23, 0x1000, 0xc0000761b0, 0x1139600, 0x10f0e20, 0x111d790, 0x111d790, 0x111d5b8, ...)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/encode.go:323 +0xe2
github.com/segmentio/encoding/json.constructMapEncodeFunc.func1(0x3, 0xc0000a2000, 0x23, 0x1000, 0xc0000761b0, 0x100cfab, 0xc000074310, 0xc000080c38, 0x68779c2f88049301, 0x680000c00008c160)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/codec.go:412 +0x93
github.com/segmentio/encoding/json.encoder.encodeStruct(0x3, 0xc0000a2000, 0x16, 0x1000, 0xc0000761b0, 0xc0000700c0, 0x14, 0x5, 0x1115408, 0x1, ...)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/encode.go:557 +0x1de
github.com/segmentio/encoding/json.constructStructEncodeFunc.func1(0x3, 0xc0000a2000, 0x16, 0x1000, 0xc0000761b0, 0xc0000a2000, 0x15, 0x1000, 0x0, 0x0)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/codec.go:467 +0x66
github.com/segmentio/encoding/json.encoder.encodeMap(0x3, 0xc0000a2000, 0xd, 0x1000, 0xc0000b7e10, 0x1139600, 0x10f0dc0, 0x111d790, 0xc000074280, 0x111d5b8, ...)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/encode.go:345 +0x2ec
github.com/segmentio/encoding/json.constructMapEncodeFunc.func1(0x3, 0xc0000a2000, 0xd, 0x1000, 0xc0000b7e10, 0x1139600, 0x10f5ae0, 0xc000074300, 0xc0000742f0, 0x0)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/codec.go:412 +0x93
github.com/segmentio/encoding/json.encoder.encodeStruct(0x3, 0xc0000a2000, 0x0, 0x1000, 0xc0000b7e10, 0xc000070080, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/encode.go:557 +0x1de
github.com/segmentio/encoding/json.constructStructEncodeFunc.func1(0x3, 0xc0000a2000, 0x0, 0x1000, 0xc0000b7e10, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/codec.go:467 +0x66
github.com/segmentio/encoding/json.constructInlineValueEncodeFunc.func1(0x3, 0xc0000a2000, 0x0, 0x1000, 0xc000076180, 0x1000, 0xc0000a2000, 0xc0000a2000, 0xc00007ce78, 0x10609c6)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/codec.go:766 +0x5e
github.com/segmentio/encoding/json.Append(0xc0000a2000, 0x0, 0x1000, 0x10f5ae0, 0xc000076180, 0x3, 0xc000080c30, 0x680000000110a2a0, 0x1, 0x68779c2f880493bd, ...)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/json.go:135 +0x100
github.com/segmentio/encoding/json.Marshal(0x10f5ae0, 0xc000076180, 0x1115408, 0x5, 0xc000080cb8, 0x0, 0x0)
        /Users/koreybarton/go/pkg/mod/github.com/segmentio/encoding@v0.1.6/json/json.go:160 +0x91
main.main()
        /Users/koreybarton/Downloads/seg-test/main.go:25 +0xec
```

**Comment by achille-roussel** [comment]
Thanks for reporting the issue @KoreyBarton ! I'm looking into it.

**Comment by Gobd** [comment]
Not sure if this a simplification or not, but same thing:

```	
	type d struct {
		S map[string]string
	}

	json.Marshal(map[string]d{
		"1": d{
			S: map[string]string{"2": "3"},
		},
	})
````

Should output `{"1":{"S":{"2":"3"}}}`

**Comment by achille-roussel** [comment]
@KoreyBarton @Gobd do you mind sharing with version of Go and the package you're testing against? I can't reproduce on Go 1.13 and with the latest version of the package (v0.1.6).

**Comment by Gobd** [comment]
v0.1.6 of this package & Go 1.13.4

**Comment by KoreyBarton** [comment]
v0.1.6 of this package and Go 1.3.5

**Comment by achille-roussel** [comment]
Actually I do have a repro if I try the code snippet with a main function that you shared, but it works OK in the tests.

I'll dig more.

**Comment by Gobd** [comment]
Looks like the test you added (and possibly others) are using the "encoding/json" package

**Comment by achille-roussel** [comment]
Thanks for pointing it out!

So the issue has to do with how the compiler inlines map addresses in the pointer-to-value field of the `interface{}` type. In your example, the struct type contains only a single map field, so apparently the compiler will inline the struct value to avoid adding an extra indirection layer.

Here's a workaround:
```go
	type d struct {
		_ struct{}
		S map[string]string
	}
```
I'll work on a fix.

**Comment by KoreyBarton** [comment]
The latest v0.1.7 release resolves my original issue. Thanks for the quick follow up.
